### ISSUE TITLE
not comptatible with thunderbird 68

### ISSUE THREAD

**Issue by inittux111** [antsar/unsafelinks#1]
I tried installing this add-on in Thunderbird 68.1.1, but when doing so I get the error that this addon is not compatible with my version of Thunderbird.  Can you make it compatible with Thunderbird 68?

**Comment by antsar** [comment]
Thanks for opening this issue. Thunderbird 68 requires extensions to be updated/rewritten for compatibility.

> Since Thunderbird 60 was released, there have been many major changes to Thunderbird’s core. Almost every extension will require modifications for compatibility with the next Thunderbird, 68. Some changes are trivial, others not.

* [About Add-ons - Legacy Extensions](https://developer.thunderbird.net/add-ons/about-add-ons#legacy-extensions)
* [Updating Legacy Extensions for Thunderbird 68](https://developer.thunderbird.net/add-ons/tb68)

I see instructions for converting to a "MailExtension with legacy support". Presumably the better long-term solution would be to rewrite as a native MailExtension. I'm not sure how many changes would be required in either case.

I'll look into this when/if I have a chance. Pull requests are also welcome.

In the meantime, I've [tagged a release](https://github.com/antsar/unsafelinks/releases/tag/1.2) to clarify that there's no compatibility with TB 68.

**Comment by antsar** [comment]
I've tagged a new release which has support for Thunderbird 68. Thanks again for reporting this.

https://github.com/antsar/unsafelinks/releases/tag/1.3

**Comment by inittux111** [comment]
> I've tagged a new release which has support for Thunderbird 68. Thanks again for reporting this.
> 
> https://github.com/antsar/unsafelinks/releases/tag/1.3

Thank you!!
