### ISSUE TITLE
Link not filtered

### ISSUE THREAD

**Issue by averter** [antsar/unsafelinks#4]
Hi. One link for a Microsoft team meeting has not been filtered for some reason. The full link is shown below. 
`<https://eur01.safelinks.protection.outlook.com/ap/t-59584e83/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fmeetup-join%2F19%253ameeting_YWE1ZDg3ZDctOTI2NC00ZDRiLWJkNTgtNDBkNzdmOGQxZmU5%2540thread.v2%2F0%3Fcontext%3D%257b%2522Tid%2522%253a%252207ef1208-413c-4b5e-9cdd-64ef305754f0%2522%252c%2522Oid%2522%253a%2522ba039afb-f03c-49d5-8bfc-09dabd362962%2522%257d&data=02%7C01%7Cdonald.duck%40disney.com%7Ccfb86d54b2944daf5bf808d7fa88debd%7C07ef1208413c4b5e9cdd64ef305754f0%7C0%7C0%7C637253338081955918&sdata=5WBcWMbJ37BfxDXOnmSD%2FSEvhPtDXWUdNmRDKSclrQQ%3D&reserved=0>`

The message has a total of 9 links and only the one above wasn't filtered. I can also send the message if necessary.

**Comment by antsar** [comment]
Hi @averter, thanks for reporting this! I hadn't encountered any safelinks URL with that `/ap/t-59584e83` component, so I didn't test the unsafelinks regex with that. This update should fix the issue for you:

https://github.com/antsar/unsafelinks/releases/tag/1.4

Please feel free to re-open the issue if that doesn't solve it.
